### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by XhmikosR** [jackyef/bundlewatch-gh-action#51]
Hey, @jackyef. It seems Node.js 16 actions are deprecated:

>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: jackyef/bundlewatch-gh-action@0.2.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Could you update to the latest packages to fix the warning?

Thanks!

**Comment by jackyef** [comment]
Thank you! This should be sorted now in 0.3.0 🙆‍♂️
